Hafele/Models/EmailSetting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hafele.Models
{
    public class EmailSetting
    {
        public string ServerName { get; set; }
        public string Port { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool UserDefaultCredentials { get; set; }
        public bool EnableSSL { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Body { get; set; }
        public bool IsBodyHtml { get; set; }
        public bool WriteEmailToDisk { get; set; }
    }
}

Hafele/Controllers/EmailSettingController.cs
using Hafele.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Hafele.Controllers
{
    public class EmailSettingController : Controller
    {
        //
        // GET: /EmailSetting/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(EmailSetting objEmail)
        {
            try
            {
                string[] to = objEmail.To.Split(',');
                string from = objEmail.From;
                string[] cc = null;
                string[] bcc = null;

                if (objEmail.CC != null)
                {
                    cc = objEmail.CC.Split(',');
                }

                if (objEmail.BCC != null)
                {
                    bcc = objEmail.BCC.Split(',');
                }

                string subject = "TEST MAIL";
                string body = objEmail.Body;

                string email_user = objEmail.Username;
                string email_pwd = objEmail.Password;

                MailMessage message = new MailMessage();
                message.From = new MailAddress(from);
                foreach (string to_item in to)
                {
                    if (!string.IsNullOrEmpty(to_item))
                    {
                        message.To.Add(to_item.Trim());
                    }
                }

                if (objEmail.CC != null)
                {
                    foreach (string cc_item in cc)
                    {
                        if (!string.IsNullOrEmpty(cc_item))
                        {
                            message.CC.Add(cc_item.Trim());
                        }
                    }
                }

                if (objEmail.BCC != null)
                {
                    foreach (string bcc_item in bcc)
                    {
                        if (!string.IsNullOrEmpty(bcc_item))
                        {
                            message.Bcc.Add(bcc_item.Trim());
                        }
                    }
                }

                message.Subject = subject;
                message.Body = objEmail.IsBodyHtml ? string.Format("<b>{0}</b>", body) : body;
                message.IsBodyHtml = objEmail.IsBodyHtml;
                SmtpClient client = new SmtpClient(objEmail.ServerName);
                client.Port = int.Parse(objEmail.Port);
                client.UseDefaultCredentials = objEmail.UserDefaultCredentials;
                client.EnableSsl = objEmail.EnableSSL;
                client.Credentials = new NetworkCredential(email_user, email_pwd);


                if (objEmail.WriteEmailToDisk)
                {
                    client.DeliveryMethod = SmtpDeliveryMethod.SpecifiedPickupDirectory;
                    client.PickupDirectoryLocation = Server.MapPath("~/emails");
                }
                else
                {
                    client.DeliveryMethod = SmtpDeliveryMethod.Network;
                }

                client.Send(message);

                SetResult("Success", Color.Green);
            }
            catch (Exception ex)
            {
                //lblResponse.Text = "Failed due to!!<br />" + ex.Message + "<br />" + ex.StackTrace + "<br />" + ex.Source + "<br />";
                SetResult("Failed due to!!<br />" + GetErrorMessage(ex), Color.Red);
            }

            return View();
        }

        public void SetResult(string text, Color color)
        {
            ViewBag.Result = string.Format("Result : {0}", text);
        }

        public string GetErrorMessage(Exception ex)
        {
            Exception exp = ex;
            string error = string.Empty;

            if (ex != null)
            {
                error += exp.Message;
                error += "<br />=========================================";
                error += exp.StackTrace;

                exp = exp.InnerException;
                while (exp != null)
                {
                    error += "<br />=========================================";
                    error += exp.Message;
                    error += "<br />=========================================";
                    error += exp.StackTrace;
                }
            }

            return error;
        }

    }
}

Hafele/Views/EmailSetting/Index.cshtml
@model Hafele.Models.EmailSetting

@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/AdminMaster.cshtml";
    Layout = null;
}

@using (Html.BeginForm("Index", "EmailSetting", FormMethod.Post))
{

    <div class="w3-container">
        <table class="w3-table-all w3-tiny">
            <tr>
                <td>
                    Server Name :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.ServerName)
                </td>
            </tr>
            <tr>
                <td>
                    Port :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.Port)
                </td>
            </tr>
            <tr>
                <td>
                    Username :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.Username)
                </td>
            </tr>
            <tr>
                <td>
                    Password :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.Password)
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    @Html.CheckBoxFor(m => m.UserDefaultCredentials) UseDefaultCredentials
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    @Html.CheckBoxFor(m => m.EnableSSL) EnableSsl
                </td>
            </tr>
            <tr>
                <td>
                    From :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.From)
                </td>
            </tr>
            <tr>
                <td>
                    To :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.To)
                </td>
            </tr>
            <tr>
                <td>
                    CC :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.CC)
                </td>
            </tr>
            <tr>
                <td>
                    BCC :
                </td>
                <td>
                    @Html.TextBoxFor(m => m.BCC)
                </td>
            </tr>
            <tr>
                <td>
                    Body :
                </td>
                <td>
                    @Html.TextAreaFor(m => m.Body)
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    @Html.CheckBoxFor(m => m.IsBodyHtml) IsBodyHtml
                    (will append &lt;b&gt;YOUR TEXT&lt;/b&gt;)
                </td>
            </tr>
            <tr>
                <td>
                    &nbsp;
                </td>
                <td>
                    @Html.CheckBoxFor(m => m.WriteEmailToDisk) Write emails to disk
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Submit" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    @if (ViewBag.Result != "")
                    {@ViewBag.Result}
                </td>
            </tr>
        </table>
    </div>

        <style>
            table, th, td {
                border: 1px solid black;
            }

            table {
                border-collapse: collapse;
                align-content: center;
                text-align: center;
            }

            th, td {
                padding: 15px;
                text-align: left;
            }
        </style>
}