Hafele/Models/OffersLeads.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hafele.Models
{
    public class OffersLeads
    {
        public string Sr { get; set; }
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string City { get; set; }
        public string Offers { get; set; }
        public string utm_source { get; set; }

        public string utm_medium { get; set; }

        public string utm_content { get; set; }
        public string utm_campaign { get; set; }

        public string Device { get; set; }
        public string utm_city { get; set; }
    
        public List<OffersLeads> OffersLeadsList { get; set; }

        public string Date { get; set; }

        public List<SelectListItem> OfferName { get; set; }
        public int[] OfferId { get; set; }

    }

  
}

Hafele/Controllers/AdminController.cs
using ClosedXML.Excel;
using Hafele.Authentication;
using Hafele.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Hafele.Controllers
{
    [CustomAdminAccessFilter]
    public class AdminController : Controller
    {
        Utility util = new Utility();
        // GET: Admin
        public ActionResult Index()
        {
            var count = Counting();
            ViewBag.OffersLeads = count["OfferLeads"].ToString();
            return View();
        }

        public Dictionary<string, string> Counting()
        {
            Dictionary<string, string> objDic = new Dictionary<string, string>();
            StringBuilder strbuil = new StringBuilder();
            DataSet ds = new DataSet();
            ds = util.Display1("Exec Proc_OffersLeads 'adminIndexCount'");
            if (ds.Tables.Count > 0)
            {
                //OfferLeads
                objDic.Add(ds.Tables[0].Rows[0]["Tbl"].ToString(), ds.Tables[0].Rows[0]["Count"].ToString());

            }
            return objDic;
        }

        #region xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Admin Profile Section Start---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        public ActionResult UpdateProfile()
        {
            DataTable dt = GetAdminDataForProfileUpdate();
            Login log = new Login();

            log.Id = dt.Rows[0]["Id"].ToString();
            log.Name = dt.Rows[0]["Name"].ToString();
            log.Emailid = dt.Rows[0]["Emailid"].ToString();
            log.Mobileno = dt.Rows[0]["Mobileno"].ToString();
            return View(log);
        }

        public DataTable GetAdminDataForProfileUpdate()
        {
            DataTable dt = new DataTable();
            try
            {
                dt = util.Display("Execute Proc_SuperAdminLogin 'GETDETAIL_FOR_UPDATE'");
            }
            catch (Exception ex)
            {

                throw ex;
            }
            return dt;
        }

        [HttpPost]
        public JsonResult UpdateProfile(Login logobj)
        {
            var response = "";

            try
            {
                response = UpdateProfileDetails(logobj.Id, logobj.Name, logobj.Emailid, logobj.Mobileno);
            }
            catch
            {
                response = "";
            }
            string Url = string.Empty;
            string Responsetype = response == "" ? "Fail" : "Success";

            return Json(new { Responsetype = Responsetype }, JsonRequestBehavior.AllowGet);
        }

        public string UpdateProfileDetails(string id, string name, string emailid, string mobileno)
        {
            string Response = string.Empty;
            try
            {
                using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@PARA", "UPDATEPROFILEDETAILS");
                    cmd.Parameters.AddWithValue("@NAME", name);
                    cmd.Parameters.AddWithValue("@EMAILID", emailid);
                    cmd.Parameters.AddWithValue("@MOBILENO", mobileno);
                    cmd.Parameters.AddWithValue("@ID", id);
                    if (util.Execute(cmd))
                    {
                        Response = "success";
                    }
                    else
                    {
                        Response = "";
                    }
                }
            }
            catch
            {

                Response = "";
            }
            return Response;
        }


        public ActionResult ChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(Login obj)
        {
            using (SqlCommand cmd = new SqlCommand("Proc_SuperAdminLogin"))
            {
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@PARA", "CHANGE_PASSWORD");
                cmd.Parameters.AddWithValue("@USERNAME", Request.Cookies["SuperAdminusername"].Value);
                cmd.Parameters.AddWithValue("@PASSWORD", obj.OldPassword);
                cmd.Parameters.AddWithValue("@NEWPASSWORD", obj.Password);
                DataTable dt = new DataTable();
                dt = util.Display(cmd);
                if (dt.Rows[0]["update"].ToString() == "correct")
                {
                    ViewBag.message = "Success";
                    ViewBag.message1 = "Your Password has been changed Successfully!";
                }
                else
                {
                    ViewBag.message = "fail";
                    ViewBag.message1 = "Sorry ! Password Could not be changed Successfully!";
                }
                ModelState.Clear(); //make blank to class property
            }
            return View();
        }

        #endregion xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx--- Billing Profile Section End---xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx


        #region xxxxxxxxxxxxxxxxxxxxxxxxxxx -- Offers Leads -- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

        public ActionResult Offers_Leads()
        {
            OffersLeads objOffersLeads = new OffersLeads();
            objOffersLeads.OffersLeadsList = OffersLeadsList();
            return View(objOffersLeads);
        }

        public List<OffersLeads> OffersLeadsList()
        {
            try
            {
                List<OffersLeads> objContactUs = new List<OffersLeads>();
                DataSet ds = new DataSet();
                ds = util.Display1("Execute Proc_OffersLeads 'get'");
                if (ds.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow dr in ds.Tables[0].Rows)
                    {
                        OffersLeads obj = new OffersLeads();
                        obj.Sr = dr["Sr"].ToString();
                        obj.Id = int.Parse(dr["Id"].ToString());
                        obj.FullName = dr["FullName"].ToString();
                        obj.Email = dr["Email"].ToString();
                        obj.MobileNo = dr["MobileNo"].ToString();
                        obj.City = dr["City"].ToString();
                        obj.Offers = dr["Offers"].ToString();
                        obj.utm_source = dr["utm_source"].ToString();
                        obj.utm_medium = dr["utm_medium"].ToString();
                        obj.utm_content = dr["utm_content"].ToString();
                        obj.utm_campaign = dr["utm_campaign"].ToString();
                        obj.Device = dr["Device"].ToString();
                        obj.utm_city = dr["utm_city"].ToString();
                        obj.Date = dr["Date"].ToString();


                        objContactUs.Add(obj);

                    }
                }
                return objContactUs;
            }
            catch (Exception ex)
            {
                LogError log = new LogError();
                log.HandleException(ex);

                ViewBag.Message = "error";
                ViewBag.Message1 = "Try again after some time.";

                TempData["Message"] = ViewBag.Message;
                TempData["Message1"] = ViewBag.Message1;

                return null;
            }
        }

        public ActionResult DeleteOffers_Leads(int? Id)
        {
            try
            {
                using (SqlCommand cmd = new SqlCommand("Proc_OffersLeads"))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@para", "delete");
                    cmd.Parameters.AddWithValue("@Id", Id);
                    if (util.Execute(cmd))
                    {
                        ViewBag.Message = "success";
                        ViewBag.Message1 = "Record deleted successfully.";

                        TempData["Message"] = ViewBag.Message;
                        TempData["Message1"] = ViewBag.Message1;

                        return RedirectToAction("Offers_Leads");
                    }
                    else
                    {
                        ViewBag.Message = "warning";
                        ViewBag.Message1 = "Record could not deleted successfully.";

                        TempData["Message"] = ViewBag.Message;
                        TempData["Message1"] = ViewBag.Message1;

                        return RedirectToAction("Offers_Leads");
                    }
                }
            }
            catch (Exception ex)
            {
                LogError log = new LogError();
                log.HandleException(ex);

                ViewBag.Message = "error";
                ViewBag.Message1 = "Try again after some time.";

                TempData["Message"] = ViewBag.Message;
                TempData["Message1"] = ViewBag.Message1;

                return RedirectToAction("Offers_Leads");
                //throw;
            }

        }

        public ActionResult DownloadOfferListExcel()
        {
            try
            {
                List<OffersLeads> objList = new List<OffersLeads>();
                DataSet ds = new DataSet();
                ds = util.Display1("Exec Proc_OffersLeads 'getExport'");

                using (XLWorkbook wb = new XLWorkbook())
                {
                    wb.Worksheets.Add(ds);
                    wb.Style.Alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    wb.Style.Font.Bold = true;

                    Response.Clear();
                    Response.Buffer = true;
                    Response.Charset = "";
                    Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

Hafele/Views/Admin/ChangePassword.cshtml
@model Hafele.Models.Login

@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

@if (ViewBag.message == "Success")
{
    <meta http-equiv="refresh" content="5; url=/Login/Logout?Usertype=SuperAdmin">
}

@using (Html.BeginForm("ChangePassword", "Admin", FormMethod.Post))
{
    <div class="right_col" role="main" style="min-height: 1602.99px;">
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Change Password</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br>
                            <div id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left">

                                @if (ViewBag.message == "Success")
                                {
                                    <div id="idalertofsuccess" class="alert alert-success alert-dismissable" style="display: block">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

                                        <span id="lblMsg">@ViewBag.message1</span>

                                    </div>
                                }
                                else if (ViewBag.message == "warning")
                                {
                                    <div id="idalertofwarning" class="alert alert-warning alert-dismissable" style="display: block">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

                                        <span id="lblmsgwarning">@ViewBag.message1</span>
                                    </div>
                                }
                                else if (ViewBag.message == "fail")
                                {
                                    <div id="idalertofdanger" class="alert alert-danger alert-dismissable" style="display: block">
                                        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

                                        <span id="lblerror">@ViewBag.message1</span>
                                    </div>
                                }
                                else
                                {
                                    <div id="idalertvalidation" class="alert alert-warning alert-dismissable" style="display: none">
                                        <a href="javascript:void();" class="close closeclienside">×</a>

                                        <span id="lblvalidationmsgwarning"></span>
                                    </div>
                                }


                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Old Password <span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.OldPassword, new { type = "password", id = "txtold", @class = "form-control col-md-7 col-xs-12", autocomplete = "off" })
                                        <label id="lblold"></label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        New Password <span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.Password, new { type = "password", id = "txtnew", @class = "form-control col-md-7 col-xs-12", autocomplete = "off" })
                                        <label id="lblnew"></label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Confirm Password <span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.ConfirmPassword, new { type = "password", id = "txtconfirm", @class = "form-control col-md-7 col-xs-12", autocomplete = "off" })
                                        <label id="lblconfirm"></label>
                                    </div>
                                </div>

                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">

                                        <input type="submit" value="Submit" id="btnsumbit" class="btn btn-success" onclick="javascript: return ChangePasswordValidation();" name="btnAction" />

                                        <input type="reset" value="Cancel" id="btnreset" class="btn btn-primary" />
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script src="@Url.Content("~/Content/Resource/Js/AdminUpdateprofile.js?version="+@DateTime.Now.Millisecond)"></script>
    <script>
        function AutoRedirectToLogin() {
            window.setTimeout(function () {
                window.location.href = '/Login/Logout?Usertype=Billing';
            }, 4000);
        }
    </script>

}

Hafele/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<div class="right_col" role="main" style="min-height: 1381px;">
    <div class="">
        <div class="row top_tiles">
            <div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <a href="~/Admin/Offers_Leads">
                    <div class="tile-stats">
                        <div class="count">@ViewBag.OffersLeads</div>
                        <h6>Offers Leads</h6>
                    </div>
                </a>
            </div>
 
        </div>





        <div class="row" style="display:none;">


            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Bar graph <small>Sessions</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Settings 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
                        <canvas id="mybarChart" width="484" height="242" style="width: 484px; height: 242px;"></canvas>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Hafele/Views/Admin/Offers_Leads.cshtml
@model Hafele.Models.OffersLeads

@{
    ViewBag.Title = "Offers_Leads";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}

<div class="right_col" role="main">
    <div class="">

        @*<div class="page-title">
            <div class="title_left">
                <h3>Offers Leads</h3>
            </div>


        </div>*@

        @using (Html.BeginForm("DownloadOfferListExcel", "Admin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-9 col-sm-12 col-xs-12 col-md-offset-1">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Offers Leads</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="title_right">
                            <div class="col-xs-12 form-group text-right ">
                                <input type="submit" value="Export To Excel" class="btn btn-success StoreDDLValueinhihhenfields" />
                            </div>
                           
                        </div>
                </div>
            </div>
                </div>
        }
        <div class="row">

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_content">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>Sr No.</th>
                                    <th>
                                        FullName
                                    </th>
                                    <th>
                                        Email
                                    </th>
                                    <th>
                                        MobileNo
                                    </th>
                                    <th>
                                        City
                                    </th>
                                    <th>
                                        Offers
                                    </th>
                                    <th>
                                        utm_source
                                    </th>

                                    <th>
                                        utm_content
                                    </th>
                                    <th>
                                        utm_campaign
                                    </th>
                                    <th>
                                        Device
                                    </th>
                                    <th>
                                        utm_city
                                    </th>
                                    <th>
                                        Datee
                                    </th>
                                    <th>Delete</th>
                                </tr>
                            </thead>

                            <tbody>

                                @if (Model.OffersLeadsList != null)
                                {
                                    foreach (var item in Model.OffersLeadsList)
                                    {
                                        <tr class="counter">
                                            <td>@Html.DisplayFor(modelItem => item.Sr)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.FullName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MobileNo)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.City)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Offers)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.utm_source)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.utm_content)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.utm_campaign)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Device)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.utm_city)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Date)
                                            </td>

                                            <td>

                                                <a href="@Url.Action("DeleteOffers_Leads", "Admin", new { id = item.Id })" title="Delete" onclick="return confirm('Are you sure you want to delete this Record?')">
                                                    <button type="button" class="btn ">
                                                        <i class="fa fa-close"></i>
                                                    </button>
                                                </a>

                                            </td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Hafele/Views/Admin/UpdateProfile.cshtml
@model Hafele.Models.Login

@{
    ViewBag.Title = "UpdateProfile";
    Layout = "~/Views/Shared/AdminMaster.cshtml";
}


<div class="right_col" role="main" style="min-height: 1500.99px;">
    <div class="">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12 col-md-offset-2">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Update Profile</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br>
                        <div id="demo-form2" data-parsley-validate="" class="form-horizontal form-label-left">



                            <div class="col-md-offset-2 col-md-6">

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                        Name <span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.Name, new { id = "txtname", @class = "form-control col-md-7 col-xs-12", autocomplete = "off" })


                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Emailid <span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.Emailid, new { id = "txtemailid", @class = "form-control col-md-7 col-xs-12", autocomplete = "off" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">
                                        Mobileno<span class="required" style="color: red;">*</span>
                                    </label>
                                    <div class="col-md-9 col-sm-6 col-xs-12">

                                        @Html.TextBoxFor(x => x.Mobileno, new { id = "txtmobileno", @class = "form-control col-md-7 col-xs-12", maxlength = "10", autocomplete = "off" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3" style="text-align: center;">
                                        @Html.HiddenFor(x => x.Id, new { id = "txtid" })
                                        <button type="button" class="btn btn-success" id="UpdateDetails">Update</button>
                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<script src="~/Content/Resource/Js/AdminUpdateprofile.js?@DateTime.Now.Millisecond"></script>